Lab1/lab1/urls.py
from django.contrib import admin
from django.urls import path
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import  settings
from django.conf.urls.static import  static
from django.urls import path, include

urlpatterns = [

    path('', user_views.landing, name='landing'),
    #path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Lab1/users/urls.py
from django.urls import path, include
from users.views import *
from django.urls import path
from users import views as user_views
app_name = 'users'

urlpatterns = [
    path('register', user_views.register, name='register'),
    path('login', user_views.login, name='login'),
    path('admin_main', user_views.admin_main, name='admin_main'),
    path('main_page', user_views.main_page, name='main_page'),
    path('logout', user_views.logout_view, name='logout'),
    path('profile/', user_views.profile_view, name='profile'),
    path('my_posts/', user_views.my_posts_view, name='my_posts'),
    path('', include('posts.urls', namespace='users')),
]

Lab1/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models

# users/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models

class CustomUserManager(BaseUserManager):
    def create_user(self, username, email=None, password=None, **extra_fields):
        email = self.normalize_email(email)
        user = self.model(username=username, email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('role', 'admin')

        return self.create_user(username, email, password, **extra_fields)

class CustomUser(AbstractUser):
    ROLE_CHOICES = (
        ('user', 'User'),
        ('blogger', 'Blogger'),
        ('admin', 'Admin'),
    )

    role = models.CharField(max_length=10, choices=ROLE_CHOICES, default='user')

    objects = CustomUserManager()

Lab1/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser

from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms
from .models import CustomUser

class LoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введіть username'}))
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Введіть password'}))

    class Meta:
        model = CustomUser
        fields = ['username',  'password']





class RegisterForm(UserCreationForm):
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введіть name'})
    )
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введіть surname'})
    )
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введіть username'})
    )
    email = forms.CharField(
        widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Введіть email'})
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Введіть пароль'})
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Підтвердіть пароль'})
    )

    # Добавляем поле role
    role = forms.ChoiceField(
        choices=[('user', 'User'), ('blogger', 'Blogger')],
        widget=forms.Select(attrs={'class': 'form-control'})
    )

    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'password1', 'password2', 'first_name', 'last_name', 'role']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Ограничиваем роли только user и blogger, если надо динамически
        self.fields['role'].choices = [
            ('user', 'User'),
            ('blogger', 'Blogger'),
        ]

Lab1/users/views.py
# Create your views here.
from django.shortcuts import render, redirect
from django.contrib import auth, messages
from django.contrib.auth import   logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, HttpResponseRedirect

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from posts.models import BlogPost
from .forms import RegisterForm, LoginForm
from django.shortcuts import render



def redirect_by_role(user):
    if not user.is_authenticated:
        return None;
    role = getattr(user, 'role', None)

    if user.is_superuser or user.is_staff:
        return redirect(reverse('users:admin_main'))
    elif role == 'user' or role=="blogger":
        return redirect(reverse('users:main_page'))

def redirect_by_role_main(user):

    role = getattr(user, 'role', None)

    if user.is_superuser or user.is_staff:
        return redirect(reverse('users:admin_main'))
    elif role == 'user' or role == "blogger":
        return redirect(reverse('users:main_page'))
    #else:
        #return redirect('home')




@login_required
def home(request):
    if request.user.role == 'admin':
        return redirect(reverse('users:admin_main'))
    else:
        return redirect(reverse('users:main_page'))



def landing(request):
    current_user = request.user
    redirect_response=redirect_by_role(current_user)
    if redirect_response:
        return redirect_response

    return render(request, 'users/landing.html')
@login_required
def admin_main(request):
    current_user = request.user
    role = getattr(current_user, 'role', None)
    if current_user.is_authenticated:
        if (role == "admin"):
            return render(request, 'users/admin_main_page.html')
        else:
            redirect_response = redirect_by_role_main(current_user)
            if redirect_response:
                return redirect_response
    return redirect(reverse('users:login'))




@login_required
def main_page(request):
    current_user = request.user
    role = getattr(current_user, 'role', None)
    if current_user.is_authenticated:
        if (role == "user" or role=="blogger"):
            context = {
                'title': 'Головна.',
                'posts': BlogPost.objects.all()

            }
            return render(request, 'users/main_page.html', context)
        else:

            redirect_response = redirect_by_role_main(current_user)
            if redirect_response:
                return redirect_response
    return redirect(reverse('users:login'))







"""@login_required
def blogger_main(request):
    current_user = request.user
    role = getattr(current_user, 'role', None)
    if current_user.is_authenticated:
        if (role == "blogger"):
            context = {
                'title': 'Блогер-головна.',
                'posts': BlogPost.objects.all()

            }
            return render(request, 'users/blogger_main_page.html', context)
        else:
            redirect_response = redirect_by_role_main(current_user)
            if redirect_response:
                return redirect_response
    return redirect(reverse('users:login'))"""



def register(request):
    if request.user.is_authenticated:
        current_user = request.user
        redirect_response = redirect_by_role(current_user)
        if redirect_response:
            return redirect_response

        """
        if (role == "user"):
            return redirect('user_main')
        elif role == "admin":
            return redirect('admin_main')
        else:
            return redirect('blogger_main')
        """

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.role = form.cleaned_data['role']
            user.save()
            return redirect(reverse('users:login'))
    else:
        form = RegisterForm()
    context = {'form': form}
    return render(request, 'users/register.html', context)


def login(request):
    if request.user.is_authenticated:
        if request.user.is_authenticated:
            current_user = request.user
            redirect_response = redirect_by_role(current_user)
            if redirect_response:
                return redirect_response

    print("Функція працює")
    if request.method == "POST":
        form = LoginForm(request, data=request.POST)
        print(form.is_valid())
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user=auth.authenticate(username=username,password=password)
            if user:
                auth.login(request,user)
        context = {'form':form}

    else:
        form = LoginForm()
        context = {'form': form}
    return render(request, "users/login.html", context)



def logout_view(request):
    logout(request)
    messages.success(request, "Ви вийшли з акаунту успішно!")
    return redirect('landing')

@login_required
def profile_view(request):
    return render(request, 'users/profile.html')

@login_required
def my_posts_view(request):
    user = request.user
    posts = BlogPost.objects.filter(author=user)
    context = {'posts': posts}
    return render(request, 'users/my_posts.html', context)

Lab1/users/templates/users/admin_main_page.html
<h1>Вітаємо, Адміністраторе {{ user.username }}!</h1>

Lab1/users/templates/users/base_user.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Landing Page</title>
   {% block css %}

{% endblock %}
</head>
<body>
<header>
    <div class="header-logo">
        <div class="logo-image">
            <img src="{% static 'image.png' %}" alt="logo">
        </div>
        <div class="logo-text">
            UFOLOGIC
        </div>
    </div>

    <div class="header-nav">
        {% if user.is_authenticated %}
            {% if user.role == "blogger" %}
                <a href="{% url 'users:main_page' %}">Пости</a>
                <a href="{% url 'users:posts:create_post' %}">Створити пост</a>
                 <a href="{% url 'users:profile' %}">Профіль</a>
            {% else %}
                <a href="{% url 'users:main_page' %}">Пости</a>
                <a href="{% url 'users:profile' %}">Профіль</a>
            {% endif %}
            <a href="{% url 'users:logout' %}">Вийти</a>
        {% else %}
            <a href="{% url 'users:login' %}">Увійти</a>
            <a href="{% url 'users:register' %}">Реєстрація</a>
        {% endif %}
    </div>
</header>
{% block content %}



{% endblock %}

<footer>
    <div class="social-networks">
        <div class="social-networks-icon">
            <a href="#"><img src="{% static 'icons/greenfacebook.png' %}" alt="Facebook"></a>
        </div>
        <div class="social-networks-icon">
            <a href="#"><img src="{% static 'icons/youtbgreen.png' %}" alt="YouTube"></a>
        </div>
        <div class="social-networks-icon">
            <a href="#"><img src="{% static 'icons/greeninstagram.png' %}" alt="Instagram"></a>
        </div>
        <div class="social-networks-icon">
            <a href="#"><img src="{% static 'icons/twittergreen.png' %}" alt="Twitter"></a>
        </div>
    </div>
    <div class="copyright">
        © 2025 UFOLOGIC, Inc.
    </div>
</footer>

</body>
</html>

Lab1/users/templates/users/landing.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Landing Page</title>
    <link rel="stylesheet" href="{% static 'css/landing.css' %}">
</head>
<body>
<header>
    <div class="header-logo">
        <div class="logo-image">
            <img src="{% static 'image.png' %}" alt="logo">
        </div>
        <div class="logo-text">
            UFOLOGIC
        </div>
    </div>
    <div class="header-nav">
        <a href="{% url 'users:login' %}">Увійти</a>
    </div>
</header>

<div class="main-content">

    {% comment %} ======== Блок 1 ======== {% endcomment %}
    <div class="block">
        <div class="block-content">
            <div class="block-text">
                <h2>Що таке UFOLOGIC?</h2>
                <p>Ви побачали НЛО, але ніхто вам не вірить. UFOLOGIC — спільнота, в якій кожен може бути почутим! Доєднуйтесь до нас!</p>
                <a href="{% url 'users:login' %}"><button class="block-btn">Реєструйтесь</button></a>

            </div>
        </div>
        <div class="block-image">
            <img src="{% static 'block1.png' %}" alt="Block 1">
        </div>
    </div>

    {% comment %} ======== Блок 2 ======== {% endcomment %}
    <div class="block">
        <div class="block-content">
            <div class="block-text">
                <h2>Щоденна публікація блогів.</h2>
                <p>Актуальне інформування щодо інцидентів по всьому світу: аномалії, привиди, викрадення людей, НЛО, прибульці і навіть більше!</p>
                <a href="{% url 'users:login' %}"><button class="block-btn">Реєструйтесь</button></a>
            </div>
        </div>
        <div class="block-image">
            <img src="{% static 'block2.jpg' %}" alt="Block 2">
        </div>
    </div>

    {% comment %} ======== Блок 3 ======== {% endcomment %}
    <div class="block">
        <div class="block-content">
            <div class="block-text">
                <h2>Створення власного блогу.</h2>
                <p>Реєструйтесь як блогер і опишіть свої враження в пості!</p>
                <a href="{% url 'users:login' %}"><button class="block-btn">Реєструйтесь</button></a>
            </div>
        </div>
        <div class="block-image">
            <img src="{% static 'block3.jpg' %}" alt="Block 3">
        </div>
    </div>


    <div class="block">
        <div class="block-content">
            <div class="block-text">
                <h2>Організація зборів.</h2>
                <p>Проведіть власний івент або приєднайтесь до вже організованого. Разом протистояти легше.</p>
                <a href="{% url 'users:login' %}"><button class="block-btn">Реєструйтесь</button></a>
            </div>
        </div>
        <div class="block-image">
            <img src="{% static 'block4.jpg' %}" alt="Block 4">
        </div>
    </div>

    {% comment %} ======== Блок 5 ======== {% endcomment %}
    <div class="block">
        <div class="block-content">
            <div class="block-text">
                <h2>Стали свідком чогось незвичайного?</h2>
                <p>Навіть якщо ви просто читач — ви можете поділитись своїм досвідом з нами!</p>
                <a href="{% url 'users:login' %}"><button class="block-btn">Реєструйтесь</button></a>
            </div>
        </div>
        <div class="block-image">
            <img src="{% static 'block5.png' %}" alt="Block 5">
        </div>
    </div>
</div>

<footer>
    <div class="social-networks">
        <div class="social-networks-icon">
            <a href="#"><img src="{% static 'icons/greenfacebook.png' %}" alt="Facebook"></a>
        </div>
        <div class="social-networks-icon">
            <a href="#"><img src="{% static 'icons/youtbgreen.png' %}" alt="YouTube"></a>
        </div>
        <div class="social-networks-icon">
            <a href="#"><img src="{% static 'icons/greeninstagram.png' %}" alt="Instagram"></a>
        </div>
        <div class="social-networks-icon">
            <a href="#"><img src="{% static 'icons/twittergreen.png' %}" alt="Twitter"></a>
        </div>
    </div>
    <div class="copyright">
        © 2025 UFOLOGIC, Inc.
    </div>
</footer>
</body>
</html>

Lab1/users/templates/users/login.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Landing Page</title>
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
</head>
<body style="height: 100%">
<div class="login-container">
    <div class="login-box">
        <h2>Увійти</h2>

        <form action="{% url 'users:login' %}" method="post" class="login-form">
            {% csrf_token %}
            {{ form.non_field_errors }}

            <div class="login-input">
                <label for="{{ form.username.id_for_label }}">Логін</label>
                {{ form.username }}
            </div>

            <div class="login-input">
                <label for="{{ form.password.id_for_label }}">Пароль</label>
                {{ form.password }}
            </div>

            <button type="submit" class="login-btn">Увійти</button>
        </form>

        <div class="register-link">
            Ще немає акаунта? <a href="{% url 'users:register' %}">Зареєструватися</a>
        </div>
    </div>
</div>
</body>

Lab1/users/templates/users/main_page.html
{% extends 'users/base_user.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="/static/css/main.css">
{% endblock %}


{% block content %}
<div class="blog-container">
    <h2 class="blog-title">Пост</h2>

    {% if posts %}
        {% for post in posts %}
            <div class="blog-post">
                {% if post.preview_image %}
                    <img src="{{ post.preview_image.url }}" alt="{{ post.title }}" class="preview-img">
                {% endif %}

                <h3>{{ post.title }}</h3>
                <p class="blog-author">
                    Автор: {{ post.author.username }} |
                    <span class="date">{{ post.created_at|date:"d.m.Y H:i" }}</span>
                </p>

                <p class="blog-content">
                    {{ post.content|truncatewords:40 }}
                </p>

                <div class="blog-footer">
                    <span>👍 {{ post.likes }}</span>
                    <span>👎 {{ post.dislikes }}</span>
                </div>

                <a href="{% url 'users:posts:post_detail' post.id %}" class="read-more">Читати далі →</a>
            </div>
        {% endfor %}
    {% else %}
        <p>Немає постів 😔</p>
    {% endif %}
</div>


{% endblock %}

Lab1/users/templates/users/my_posts.html
{% extends 'users/base_user.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="/static/css/main.css">
{% endblock %}


{% block content %}
<div class="blog-container">
    <h2 class="blog-title">Мої пости</h2>

    {% if posts %}
        {% for post in posts %}
            <div class="blog-post">
                {% if post.preview_image %}
                    <img src="{{ post.preview_image.url }}" alt="{{ post.title }}" class="preview-img">
                {% endif %}

                <h3>{{ post.title }}</h3>

                <p class="blog-content">
                    {{ post.content|truncatewords:40 }}
                </p>

                <div class="blog-footer">
                    <span>👍 {{ post.likes }}</span>
                    <span>👎 {{ post.dislikes }}</span>
                </div>

                <a href="{% url 'users:posts:blogger_posts_detail' post.id %}" class="read-more">Детально</a>
            </div>
        {% endfor %}
    {% else %}
        <p>У вас немає постів 😔</p>
    {% endif %}
</div>


{% endblock %}

Lab1/users/templates/users/profile.html
{% extends 'users/base_user.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/profile.css' %}">
{% endblock %}

{% block content %}
<div class="profile-container">
        <h2>👤 Профіль користувача</h2>
        <div class="profile-info">
            <p><strong>Ім’я користувача:</strong> {{ user.username }}</p>
            <p><strong>Ім’я:</strong> {{ user.first_name }}</p>
            <p><strong>Прізвище:</strong> {{ user.last_name }}</p>
            <p><strong>Email:</strong> {{ user.email }}</p>
            <p><strong>Роль:</strong>
                {% if user.role == "blogger" %}
                    <span class="role blogger">Блогер</span>
                {% elif user.role == "admin" %}
                    <span class="role admin">Адмін</span>
                {% else %}
                    <span class="role user">Користувач</span>
                {% endif %}
            </p>
            <p><strong>Дата приєднання:</strong> {{ user.date_joined|date:"d.m.Y" }}</p>
        </div>

        <hr>

        {% if user.role == "blogger" %}
            <div class="blogger-section">
                <h3>Блогерські можливості</h3>
                <div class="blogger-links">
                    <a href="{% url 'users:my_posts' %}" class="btn-check-posts">Переглянути мої пости</a>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}

Lab1/users/templates/users/register.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Landing Page</title>
    <link rel="stylesheet" href="{% static 'css/register.css' %}">
</head>


<div class="register-container">
    <div class="register-box">
        <h2>Реєстрація</h2>

        <form method="post">
            {% csrf_token %}

            <div class="form-group">
                <label for="{{ form.first_name.id_for_label }}">Ім’я</label>
                {{ form.first_name }}
                {{ form.first_name.errors }}
            </div>

            <div class="form-group">
                <label for="{{ form.last_name.id_for_label }}">Прізвище</label>
                {{ form.last_name }}
                {{ form.last_name.errors }}
            </div>

            <div class="form-group">
                <label for="{{ form.username.id_for_label }}">Логін</label>
                {{ form.username }}
                {{ form.username.errors }}
            </div>

            <div class="form-group">
                <label for="{{ form.email.id_for_label }}">Електронна пошта</label>
                {{ form.email }}
                {{ form.email.errors }}
            </div>

            <div class="form-group">
                <label for="{{ form.password1.id_for_label }}">Пароль</label>
                {{ form.password1 }}
                {{ form.password1.errors }}
            </div>

            <div class="form-group">
                <label for="{{ form.password2.id_for_label }}">Підтвердження пароля</label>
                {{ form.password2 }}
                {{ form.password2.errors }}
            </div>

            <div class="form-group">
                <label for="{{ form.role.id_for_label }}">Роль</label>
                {{ form.role }}
                {{ form.role.errors }}
            </div>

            <button type="submit" class="btn btn-primary">Зареєструватися</button>
        </form>

        <div class="login-link">
            Вже маєте акаунт? <a href="{% url 'users:login' %}">Увійти</a>
        </div>
    </div>
</div>